apiVersion: v1
kind: Service
metadata:
  name: redis-slave-ha
  labels:
    app: "{{ .Chart.Name }}-slave"
spec:
  ports:
  - port: 6379
    name: redis-slave
  clusterIP: None
  selector:
    app: "{{ .Chart.Name }}-slave"
