kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Chart.Name }}-master"
  annotations: 
    {{- if .Values.persistence.storageClass }}
      volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.storageClass | quote }}
    {{- else }}
      volume.alpha.kubernetes.io/storage-class: default
    {{- end }}
spec:
  accessModes: 
    - {{ .Values.persistence.accessModes | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Chart.Name }}-slave"
  annotations: 
    {{- if .Values.persistence.storageClass }}
      volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.storageClass | quote }}
    {{- else }}
      volume.alpha.kubernetes.io/storage-class: default
    {{- end }}
spec:
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}