apiVersion: v1
kind: Service
metadata:
  name: redis-master-ha
  labels:
    app: "{{ .Chart.Name }}-master"
spec:
  ports:
  - port: 6379
    name: redis-master
  clusterIP: None
  selector:
    app: "{{ .Chart.Name }}-master"
